
extends: eslint:recommended

rules:
  arrow-parens: error
  arrow-spacing: error
  comma-dangle: [error, always-multiline]
  no-constant-condition: off
  no-unexpected-multiline: error
  no-unreachable: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-template: error
  quotes: [error, double]
  semi: [error, never]
  strict: [error, global]

env:
    node: true
    es6: true

parserOptions:
    sourceType: module
