parser: babel-eslint

extends:
    - eslint:recommended
    - plugin:react/recommended

plugins:
    - react

rules:
  arrow-parens: error
  arrow-spacing: error
  comma-dangle: [error, always-multiline]
  no-console: off
  no-constant-condition: off
  no-unexpected-multiline: error
  no-unreachable: error
  no-unused-vars: [error, { argsIgnorePattern: "_" }]
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-template: error
  quotes: [error, double]
  semi: [error, never]
  strict: [error, global]

  react/prop-types: off

env:
    browser: true
    es6: true

settings:
    react:
        pragma: h
